### ISSUE TITLE
r5638 doesn't compile with mingw 4.5.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [snowyu/libtorrent#202]
```
rsa.cpp fails to compile with these error messages:

src\rsa.cpp: In function 'bool libtorrent::generate_rsa_keys(char*, int*, char*,
 int*, int)':
src\rsa.cpp:108:1: error: jump to label 'getout'
src\rsa.cpp:99:45: error:   from here
src\rsa.cpp:102:17: error:   crosses initialization of 'unsigned char* priv'
src\rsa.cpp:101:17: error:   crosses initialization of 'unsigned char* pub'
src\rsa.cpp:108:1: error: jump to label 'getout'
src\rsa.cpp:98:44: error:   from here
src\rsa.cpp:102:17: error:   crosses initialization of 'unsigned char* priv'
src\rsa.cpp:101:17: error:   crosses initialization of 'unsigned char* pub'


I use this command line to compile:
bjam -q --without-python --toolset=gcc variant=release link=static 
runtime-link=shared encryption=openssl logging=none geoip=static dht-support=on 
boost=source character-set=unicode iconv=on

The solution is quite simple. Just wrap lines 101-104 in brackets in rsa.cpp
```

Original issue reported on code.google.com by `hammered...@gmail.com` on 27 May 2011 at 5:28
