### ISSUE TITLE
Error when building with mingw under Windows

### ISSUE THREAD

**Issue by GoogleCodeExporter** [snowyu/libtorrent#518]
```
I am trying to build with mingw 4.8.0 under Windows XP sp2 latest RC_0_16.

I build with this cmd in msys: BOOST_ROOT=/c/QBITTORRENT/boost_1_54_0/ 
./configure --enable-encryption --disable-shared --enable-static 
--with-openssl=/c/QBITTORRENT/install_mingw/ 
--prefix=/c/QBITTORRENT/install_mingw/ 
CFLAGS=-I/c/QBITTORRENT/install_mingw/include 
LDFLAGS=-L/c/QBITTORRENT/install_mingw/lib LIBS=-lz -lgdi32 CFLAGS="-Os -s 
-mmmx -msse -msse2 -ffunction-sections -fdata-sections -fomit-frame-pointer 
-fpredictive-commoning" LDFLAGS="-Wl,-s -Wl,--gc-sections -Wl,--relax 
-Wl,--sort-common -Wl,-s -Wl,--as-needed -static-libgcc -static-libstdc++"


And I get this error:
file.cpp: In member function 'bool 
libtorrent::file::set_size(libtorrent::size_type, 
boost::system::error_code&)':file.cpp:1982:68: error: cannot convert 'const 
wchar_t*' to 'LPCSTR {aka const char*}' for argument '1' to 'DWORD 
GetCompressedFileSizeA(LPCSTR, LPDWORD)'    offs.LowPart = 
GetCompressedFileSize(m_path.c_str(), &high_dword);
```

Original issue reported on code.google.com by `hammered...@gmail.com` on 20 Sep 2013 at 9:07
